---
apiVersion: v1
kind: Namespace
metadata:
  name: scratch
  labels:
    name: scratch

---
apiVersion: v1
kind: LimitRange          # Scoped to containers in scratch namespace
metadata:
  name: scratch-defaults
  namespace: scratch
spec:
  limits:
    - type: Container
      defaultRequest:
        memory: 50M
        cpu: 100m
      default:
        memory: 100M
        cpu: 200m
      min:
        memory: 50M
        cpu: 100m
      max:
        memory: 250M
        cpu: 400m

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: tight
  namespace: scratch
spec:
  hard:
    pods: 6
    requests.cpu: 800m
    requests.memory: 800M
    limits.cpu: 1000m
    limits.memory: 1G