---
apiVersion: batch/v1
kind: Job
metadata:
  name: package-check
spec:
  template:
    metadata:
      name: package-check
    spec:
      containers:
        - name: package-check
          image: ubuntu
          command: ["dpkg-query", "-l"]
      restartPolicy: Never
