apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-deck
  labels:
    app: {{ template "fullname" . }}
    component: deck
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: 9000
      nodePort: 31006
  selector:
    app: {{ template "fullname" . }}
    component: deck
